### ISSUE TITLE
Stream from torrent while being downloaded using ExoPlayer2

### ISSUE THREAD

**Issue by halibegic** [TorrentStream/TorrentStream-Android#30]
Hi, first of all great lib but I'm wondering if it's possible to stream from torrent while downloading. Now I need to wait for "on stream ready" event and then to play the file. Thank You.

**Comment by vonclutch** [comment]
Hum, in fact you stream when the file is downloaded. The event "on stream rdy" means you have downloaded enough pieces of the file to start streaming without interuption ( it's first one and the last one to determine the torrent ans then the 3 after the one for starting streaming ). It's normal if it's a bit slow, android devices generaly are not that good  compared to a computer and the stream can start after 1min or 2 in the worst case.

**Comment by halibegic** [comment]
Ok I understand. Thank You.

**Comment by halibegic** [comment]
Just one more question :) How to handle when the user seeks e.g. to half of the video, and there is no pieces downloaded? Thank You.

**Comment by se-bastiaan** [comment]
That's a question we cannot answer for you, you're building an app and should decide for yourself what the correct behaviour is. Although [TorrentStreamServer-Android](https://github.com/TorrentStream/TorrentStreamServer-Android) might be what you're looking for if you want it to continue to play.

**Comment by halibegic** [comment]
Ok, thank You :+1:
