### ISSUE TITLE
Works the first time

### ISSUE THREAD

**Issue by royhid** [TorrentStream/TorrentStream-Android#34]
Hi,
  I have followed the example and everything works...except...the second time around it's doesn't start the download.

It's probably not your issue, but just in case i thought i'd check.

I used your sample, which i an activity of its own called by mine when i need to stream a file. All is great, until i leave the activity, and re-open it the next time its needed. This time however it doesn't start the download.
If i kill the app, and restart it again it works.

As i said, it maybe the way i'm handling the activity, but i cant see why this would be. the onCreate is the same as your sample.

Hope you can help.

**Comment by se-bastiaan** [comment]
Are you stopping the download when the activity is killed?

**Comment by royhid** [comment]
Hi, yes i'm calling stopStream() when leaving. Actually, i've been testing further and it seems sometimes it does work a few times after the first time, but it takes a long time to get the stream ready. However, the first time it doesnt matter which stream it is it starts up in about 10 secs, and then the next time either doesnt or takes over a minute for the same torrent.

**Comment by se-bastiaan** [comment]
Are you deleting the video file after stopping the stream? That might make a difference.

**Comment by royhid** [comment]
Hi, the file gets deleted using the removeFilesAfterStop(true) on the torrentoptions object.
Is it better to use this flag? I don't want to have to delete files myself via code.

**Comment by se-bastiaan** [comment]
Can you check if the files are really being deleted?
