### ISSUE TITLE
TorrentInfoException: No torrent info could be found or read

### ISSUE THREAD

**Issue by sevar83** [TorrentStream/TorrentStream-Android#38]
Hi, I've started receiving the following error few months ago. It's not related to the new 2.4.0 version! The problems happens both on 2.3.0 and 2.4.0.

`com.github.se_bastiaan.torrentstream.exceptions.TorrentInfoException: **No torrent info could be found or read**
                               at com.github.se_bastiaan.torrentstream.TorrentStream.getTorrentInfo(TorrentStream.java:219)
                               at com.github.se_bastiaan.torrentstream.TorrentStream.access$1200(TorrentStream.java:52)
                               at com.github.se_bastiaan.torrentstream.TorrentStream$7.run(TorrentStream.java:306)
                               at android.os.Handler.handleCallback(Handler.java:789)
                               at android.os.Handler.dispatchMessage(Handler.java:98)
                               at android.os.Looper.loop(Looper.java:164)
                               at android.os.HandlerThread.run(HandlerThread.java:65)`

Actually `TorrentInfoException` swallows the cause exception but I've set a breakpoint to see what it is:

`expected value (list, dict, int or string) in bencoded string`

I think the tracker which I use to test just changed something in the torrent format and it stopped working after that moment. But it works with desktop torrent clients. I can send you a sample torrent file if you wish.

**Comment by se-bastiaan** [comment]
Can you find out what the full exception is? And maybe provide me with an example torrent?
I already changed the TorrentInfoException on the develop branch to provide the cause exception, that definitely better.

**Comment by sevar83** [comment]
I've found it. I used an http link to the torrent. But the library uses `HttpUrlConnection` without auth, cookies and stuff so the response was the login HTML page. I should've figured it out earlier but it worked fine for few weeks. Then maybe the server started to enforce authorization with my knowing.

**Comment by se-bastiaan** [comment]
Aaah cool, thank makes sense. Let me know if the `file://` protocol works.

**Comment by sevar83** [comment]
@se-bastiaan, Yes, it works. However I've few questions.
1. I have a misunderstanding about why playback starts at different values of "TorrentStatus.bufferProgress". I suppose it should start at 100% but I've seen sometimes it starts much earlier - like 40%. And what is the default value of the prebuffer?
2. Is seeking forward and backward supported?

**Comment by se-bastiaan** [comment]
1. It's possible that suddenly all the pieces that have been downloaded for 'buffering' (it's not really a buffer). The minimum amount of buffered pieces is 2, the maximum 20. And the amount that's actually buffered is based on the `prepareSize` value given in `TorrentOptions`.

2. This one's in the [FAQ](https://github.com/TorrentStream/TorrentStream-Android/wiki/FAQ) ;)

**Comment by sevar83** [comment]
Thank you for the answer! Sorry that I'm not yet well prepared for this conversation because now I'm in an earlier stage of the project but it's good to have a clear plan about the future. So, about:
1. Ok, I assume it's all fine. Maybe I should adjust the `prepareSize` to be proportional to the video compression bandwidth? Because currently it's a fixed value of 15MB.
2. I don't use TorrentStreamServer-Android yet. But in order to get the seek support is it preferable to start using your server lib and launch the VLC app with the HTTP stream url? I should try the sample again btw.

**Comment by se-bastiaan** [comment]
1. It completely depends on the video. The theory is that you have the start/end of the file so that the container is readable by the video player.
2. You can try it, I've had it working in VLC but it's not perfect. Especially when the torrent doesn't have a lot of seeders and/or the download speed is low. If you have a video player that would just read from an empty file and a way to select the interesting bytes then that would work too, but the easiest way I could think of to get the current position in bytes was via HTTP.
