### ISSUE TITLE
Fast forward and rewind the video in Player

### ISSUE THREAD

**Issue by xeeoon** [TorrentStream/TorrentStream-Android#39]
After streamReady,  The video can be played normally, But if I seek the progress bar to Fast forward and rewind, the player will get stucked. Here is the video：http://67.216.209.139/vi.mp4
How to buffer the specific location of video？

**Comment by se-bastiaan** [comment]
You can find an answer in the FAQ and any of the previous issues asking a similar question.
 [https://github.com/TorrentStream/TorrentStream-Android/wiki/FAQ] (FAQ)
