### ISSUE TITLE
support  the magnet？？？

### ISSUE THREAD

**Issue by yedajiang44** [TorrentStream/TorrentStream-Android#45]
this lib support  the magnet？？？Why don't work when I use magnet links？？

```java
        TorrentOptions torrentOptions = new TorrentOptions.Builder()
                .saveLocation(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS))
                .removeFilesAfterStop(true)
                .build();
        TorrentStream torrentStream = TorrentStream.init(torrentOptions);
        torrentStream.addListener(new TorrentListener() {
            @Override
            public void onStreamPrepared(Torrent torrent) {
                Timber.e("onStreamPrepared");
                torrent.startDownload();
            }

            @Override
            public void onStreamStarted(Torrent torrent) {
                Timber.e("onStreamStarted");
            }

            @Override
            public void onStreamError(Torrent torrent, Exception e) {
                Timber.e("onStreamError");
            }

            @Override
            public void onStreamReady(Torrent torrent) {
                Timber.e("onStreamReady");
            }

            @Override
            public void onStreamProgress(Torrent torrent, StreamStatus streamStatus) {
                Timber.e("onStreamProgress"+":progress="+streamStatus.progress+",bufferProgress="+streamStatus.bufferProgress+",downloadSpeed="+streamStatus.downloadSpeed);
            }

            @Override
            public void onStreamStopped() {
                Timber.e("onStreamStopped");
            }
        });
        torrentStream.startStream(torrentUrl);

```
when torrentUrl is a torrent , it's work and download flie
```java
String  torrentUrl="http://xxxxxxxx.torrent";
```
but when torrentUrl is a magnet link , don't work , and the console without any logs
```java
String torrentUrl="magnet:?xt=urn:btih:88594aaacbde40ef3e2510c47374ec0aa396c08e&dn=bbb%5Fsunflower%5F1080p%5F30fps%5Fnormal.mp4&tr=udp%3A%2F%2Ftracker.openbittorrent.com%3A80%2Fannounce&tr=udp%3A%2F%2Ftracker.publicbt.com%3A80%2Fannounce&ws=http%3A%2F%2Fdistribution.bbb3d.renderfarming.net%2Fvideo%2Fmp4%2Fbbb%5Fsunflower%5F1080p%5F30fps%5Fnormal.mp4";
```

**Comment by vonclutch** [comment]
Hey, 

There is a bug with magnet torrents, some trakers are just broken with frostwire it just pause the torrent or take more than 1min/2min to launch the download.
To avoid such behavior you need to destroy the torrent if it download from magnet after receive metadata, create a torrent file from the metada and launch a new torrent from the torrent file you create.

With this method your download start after 10/15sec instead of 1/2min.
 if you need some code ( it's not the best but it worked :) )

**Comment by se-bastiaan** [comment]
Is that a problem with jlibtorrent or Frostwire? Fetching of the magnet is entirely split from the download ([TorrentStream.java#L185](https://github.com/TorrentStream/TorrentStream-Android/blob/develop/library/src/main/java/com/github/se_bastiaan/torrentstream/TorrentStream.java#L185)) what I understand now is that the [magnet download](https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/SessionManager.java#L526) inside the library doesn't work? Moreover, I can't find any issues mentioning this problem?

**Comment by vonclutch** [comment]
There is some issues on jlibtorrent's github about this and it's still not fixed yet.
[issue on frostwire-jlibtorrent](
https://github.com/frostwire/frostwire-jlibtorrent/issues/174)

So some people don't use download magnethe from jlibttorent library, they prefer to download metadata and create a torrent file.

**Comment by se-bastiaan** [comment]
> So some people don't use download magnethe from jlibttorent library, they prefer to download metadata and create a torrent file.
That is exactly what happens in the code: https://github.com/TorrentStream/TorrentStream-Android/blob/develop/library/src/main/java/com/github/se_bastiaan/torrentstream/TorrentStream.java#L185

The issues mentions that the torrent is added but is paused. I cannot reproduce that, the sample app just doesn't receive any metadata at all.

**Comment by vonclutch** [comment]
I just add the alert.type  `METADATA_RECEIVED` in your [TorrentAddedAlertListener](https://github.com/TorrentStream/TorrentStream-Android/blob/develop/library/src/main/java/com/github/se_bastiaan/torrentstream/listeners/TorrentAddedAlertListener.java#L36)  

`        case METADATA_RECEIVED:
                MetadataReceivedAlert metadataAlert = ((MetadataReceivedAlert) alert);
                byte[] bytes = null;

                int size = metadataAlert.metadataSize();
                int maxSize = 2 * 1024 * 1024;

                if (0 < size && size <= maxSize)
                    bytes = metadataAlert.torrentData(true);

                torrentMetadata(bytes, metadataAlert.handle().infoHash().toHex(), (MetadataReceivedAlert) alert);
                break;`


and to create the file i just check if i'ts a magnet and restart the process.

`            if (isMagnet) {
                    File dataDir = new File(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS) + "/torrents/");

                    if (!dataDir.exists()) {
                        if (!dataDir.mkdir()) {
                            throw new FileNotFoundException();
                        }
                    }

                    File torrentFile = new File(dataDir, hash);

                    if (!torrentFile.exists()) {
                        if (!torrentFile.createNewFile()) {
                            throw new FileNotFoundException();
                        }

                        try (FileOutputStream stream = new FileOutputStream(torrentFile)) {
                            stream.write(data);
                        }
                    }

                    String pathToTorrent = torrentFile.getAbsolutePath();

                    if (streamingThread != null)
                        streamingThread.interrupt();
                    if (streamingHandler != null)
                        streamingHandler.removeCallbacksAndMessages(null);

                    if (currentTorrent != null) {
                        currentTorrent.pause();
                        removeListener(currentTorrent);
                        remove(currentTorrent.getTorrentHandle());
                        currentTorrent = null;
                    }

                    startStream(pathToTorrent);
                }
            } catch(Exception e){
                e.printStackTrace();
            }`

**Comment by yedajiang44** [comment]
@se-bastiaan First of all, I'm very sorry for my late reply , and
Thank you very much for your reply！
I don't know more about magnet link, because this magnet link is from your demo。。。

**Comment by se-bastiaan** [comment]
I know that the magnet is from the example, but that doesn't mean that the trackers are up and more specifically: that DHT is working in your situation.

Alas, I do not think I'll be able to fix this. It seems to be something upstream. I could try using the `download` method from `TorrentSession` instead of `fetchMagnet` but I don't have time for it.

**Comment by se-bastiaan** [comment]
@vonclutch I don't think I completely understand what you mean.

There is already different behaviour based on what kind of url is passed to [getTorrentInfo](https://github.com/TorrentStream/TorrentStream-Android/blob/develop/library/src/main/java/com/github/se_bastiaan/torrentstream/TorrentStream.java#L185).

If it's a magnet `fetchMagnet` is called (which is _blocking_):
```
            byte[] data = torrentSession.fetchMagnet(torrentUrl, 30000);
            if (data != null)
                try {
                    return TorrentInfo.bdecode(data);
                } catch (IllegalArgumentException e) {
                    throw new TorrentInfoException(e);
                }
```
This decodes the data array into `TorrentInfo` which can be used to download the torrent. The `METADATA_RECEIVED` should never be called based on this code iirc.

To compare this to a regular `.torrent` file: bytes are read from the file into a data array which decodes in [the same way](https://github.com/TorrentStream/TorrentStream-Android/blob/develop/library/src/main/java/com/github/se_bastiaan/torrentstream/TorrentStream.java#L216).

**Comment by yedajiang44** [comment]
@se-bastiaan I get it , thank you~~~~~~~~~

**Comment by vonclutch** [comment]
@se-bastiaan frostwire used the same for the `fetchmagnet()` , they just listen the `METADATA_RECEIVED` and return the byte[] from this. I didn't want to rewrite a lot so i make it fast and easier ( i just bypass the fetchmagnet and make it by myself) and re-start with a file.

[SessionManager#fetchmagnet()](https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/SessionManager.java#L587)

Clearly something is wrong with the lib, delay or even no download at all for magnet. From what i saw on their issue it could come from `TorrentHandle` but could come from anywhere rly :/
