### ISSUE TITLE
Info

### ISSUE THREAD

**Issue by DeevD** [TorrentStream/TorrentStream-Android#47]
Support Pause , Resume torrent ?

**Comment by se-bastiaan** [comment]
https://github.com/TorrentStream/TorrentStream-Android/blob/develop/library/src/main/java/com/github/se_bastiaan/torrentstream/Torrent.java#L157
https://github.com/TorrentStream/TorrentStream-Android/blob/develop/library/src/main/java/com/github/se_bastiaan/torrentstream/Torrent.java#L150

you can already do this
