### ISSUE TITLE
update frostwire-jlibtorrent to 1.2.0.18

### ISSUE THREAD

**Issue by vonclutch** [TorrentStream/TorrentStream-Android#48]
There are a lot of bugs fix between  1.2.0.16 /  1.2.0.18 

https://github.com/frostwire/frostwire-jlibtorrent/blob/master/changelog.txt

**Comment by se-bastiaan** [comment]
Well, it would be weird if there was nothing to fix in between releases. If the latest was in January. :p
They look like mainly libtorrent changes.

**Comment by vonclutch** [comment]
Thanks,  i'll try this :)
