### ISSUE TITLE
Open multiple torrent

### ISSUE THREAD

**Issue by destroyxx** [TorrentStream/TorrentStream-Android#52]
Hello,
If a torrent has for example 5 videos. How can I select the video to stream it ? And why VLC can't open a video ? I am obliged to use Mx Player. Thx

**Comment by se-bastiaan** [comment]
You should be able to use the [Torrent#setSelectedFileIndex](https://github.com/TorrentStream/TorrentStream-Android/blob/develop/library/src/main/java/com/github/se_bastiaan/torrentstream/Torrent.java#L174). I cannot help you with opening videos.

**Comment by destroyxx** [comment]
Ok thx
