### ISSUE TITLE
Why add last pieces to the preparePieces list?

### ISSUE THREAD

**Issue by abbasshah17** [TorrentStream/TorrentStream-Android#53]
In [Torrent.startDownload()](https://github.com/TorrentStream/TorrentStream-Android/blob/develop/library/src/main/java/com/github/se_bastiaan/torrentstream/TorrentStream.java) last pieces of the selected torrent file are added to the `preparePieces` list, from what I understand unless each piece is downloaded in the list the playback will not start.

    for (int i = 0; i < piecesToPrepare; i++) {
        // Preparing to download the last pieces of the selected torrent file.
        indices.add(lastPieceIndex - i);
        torrentHandle.piecePriority(lastPieceIndex - i, Priority.SEVEN);
        torrentHandle.setPieceDeadline(lastPieceIndex - i, 1000);
    }

    for (int i = 0; i < piecesToPrepare; i++) {
        // Preparing to download the first pieces of the selected torrent file.
        indices.add(firstPieceIndex + i);
        torrentHandle.piecePriority(firstPieceIndex + i, Priority.SEVEN);
        torrentHandle.setPieceDeadline(firstPieceIndex + i, 1000);
    }

    preparePieces = indices;

As far as I can tell downloading only the first pieces should be sufficient to start playback. Is there any particular reason why you do?

While researching ways to initiate playback I stumbled across this [exo-player thread](https://github.com/google/ExoPlayer/issues/4212#issuecomment-387079861), which hints at video metadata sometimes being present at the end of the file. Is this why you do it or some other reason?

**Comment by se-bastiaan** [comment]
> which hints at video metadata sometimes being present at the end of the file.

That's exactly the reason.

**Comment by abbasshah17** [comment]
Then how do you make sure that the required information is completely downloaded, I'm talking in terms of size, how do you make sure you've downloaded the all the required pieces.

In case we are downloading them blindly, is there a way to know firsthand which pieces should be downloaded? So that we only download the required pieces.

Also I realize it is out of the scope for this question, but can you also provide a reference where I can further look into different video types which describes the end-of-file-meta-data behavior.

**Comment by abbasshah17** [comment]
Thanks a lot.
