### ISSUE TITLE
Help with using the library

### ISSUE THREAD

**Issue by rajatpundir** [TorrentStream/TorrentStream-Android#55]
Hi, thanks for creating this library. I simply want to download a torrent that contains some files, I don't need to play them. I tried sample and it worked great but below code doesn't seem to be working, am I doing something wrong? (I am using 2.5.0)

`class FragmentDownloads : Fragment(), TorrentListener {
    override fun onStreamReady(torrent: Torrent?) {
        println("Torrent : onStreamReady")
    }

    override fun onStreamPrepared(torrent: Torrent?) {
        println("Torrent : onStreamPrepared")
        // If you set TorrentOptions#autoDownload(false) then this is probably the place to call
        // torrent.startDownload();
    }

    override fun onStreamStopped() {
        println("Torrent : onStreamStopped")
    }

    override fun onStreamStarted(torrent: Torrent?) {
        println("Torrent : onStreamStarted")
    }

    override fun onStreamProgress(torrent: Torrent?, status: StreamStatus?) {
        println("Torrent : onStreamProgress")
        println(status?.bufferProgress)
    }

    override fun onStreamError(torrent: Torrent?, p1: Exception?) {
        println("Torrent : onStreamError")
    }

    var torrentStream: TorrentStream? = null

    override fun onCreateView(inflater: LayoutInflater, container: ViewGroup?, savedInstanceState: Bundle?): View? {
        val v = inflater.inflate(R.layout.fragment_downloads, container, false)
        return v
    }

    override fun onViewCreated(view: View, savedInstanceState: Bundle?) {
        super.onViewCreated(view, savedInstanceState)
        doAsync {
            val torrentOptions = TorrentOptions.Builder()
                .saveLocation(Environment.getExternalStoragePublicDirectory(Environment.DIRECTORY_DOWNLOADS))
                .removeFilesAfterStop(true)
                .build()
            torrentStream = TorrentStream.init(torrentOptions)
            torrentStream!!.addListener(this@FragmentDownloads)
            var magnet = "magnet:?whateverurl"
            torrentStream!!.startStream(magnet)
            println("STARTED")
        }
    }

}`

**Comment by rajatpundir** [comment]
Logs
`2019-07-26 23:01:19.578 16475-18037/ I/System.out: STARTED
2019-07-26 23:01:19.797 16475-18035/ W/OpenGLRenderer: Failed to choose config with EGL_SWAP_BEHAVIOR_PRESERVED, retrying without...
2019-07-26 23:01:19.804 16475-18035/ D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 0 0
2019-07-26 23:01:19.805 16475-18035/ D/EGL_emulation: eglCreateContext: 0x7a37aa88a860: maj 2 min 0 rcv 2
2019-07-26 23:01:19.807 16475-18035/ D/EGL_emulation: eglMakeCurrent: 0x7a37aa88a860: ver 2 0 (tinfo 0x7a37aa818c80)
2019-07-26 23:01:19.827 16475-18035/ W/Gralloc3: mapper 3.x is not supported
2019-07-26 23:01:19.880 16475-18035/ D/EGL_emulation: eglMakeCurrent: 0x7a37aa88a860: ver 2 0 (tinfo 0x7a37aa818c80)
2019-07-26 23:01:19.887 16475-18035/ D/eglCodecCommon: setVertexArrayObject: set vao to 0 (0) 1 0`

**Comment by se-bastiaan** [comment]
Are those all the logs you have? The process of the first message and the others is different so it seems.

**Comment by rajatpundir** [comment]
Yeah, those were all the logs and I figured that all other lines except first were due to frame skipping because of some kind of weird freezing moments that my Ubuntu goes under. I will try to investigate it a bit more and report my findings.

**Comment by rajatpundir** [comment]
I tested sample app a bit more, how can I change the selectedFileIndex from -1 to something I know beforehand, I am doing this in onStreamStarted but even then it creates an unnecessary file correponding to -1 or largest file. Would I need to extend TorrentStream class?

In the torrent of my interest, I have a directory containing bunch of video files and my use case is that I have to download the file whose index I already know but may not not be the largest. Even when I set the selectedFileIndex in onStreamStarted, the torrent doesn't seem to download. And, if I don't change the selectedFileIndex, the torrent seems to download but in a strange way, it says it downloaded the 100MB file when it had only downloaded some 8MB.

**Comment by se-bastiaan** [comment]
Are you trying to download a video file? If there is none in the meta of the torrent it won't do anything.

**Comment by rajatpundir** [comment]
Yes I am downloading a video file. It's just that I can't seem to get the Torrent Stream example to work in another app, after adding its jitpack repo to the build.

**Comment by rajatpundir** [comment]
After some more unsuccessful attempts, I tried a similar project at https://github.com/masterwok/simple-torrent-android which seems to be working for my use case. Anyway, thanks for all the help. I am closing this issue.
