### ISSUE TITLE
Unable to start stream

### ISSUE THREAD

**Issue by amankapur007** [TorrentStream/TorrentStream-Android#57]
Hi,

First of all thanks for providing us the code .

I am having some issue with the sample code provided. 
I am following the same step mentioned in the sample app in my app , wat i can see is neither the streaming nor downloading starts . I also dnt get any error message . Can you please help me.

Sample app also not working , after start stream , nothing happens , neither the progress bar increase's nor file getting downloaded.

**Comment by amankapur007** [comment]
Sample app also not working , after start stream , nothing happens , neither the progress bar increase's nor file getting downloaded.

**Comment by se-bastiaan** [comment]
You should be able to add some logging to the sample to find out what is happening exactly.
Maybe try https://github.com/masterwok/simple-torrent-android to see if it works for you.
