### ISSUE TITLE
bufferProgress does not finish

### ISSUE THREAD

**Issue by nostupidity** [TorrentStream/TorrentStream-Android#61]
I have to be honest this is the most unintuitive library I have used, It is probably because a knowledge of Torrent is needed and part of it is probably because of this library. My issue is whenever the download starts bufferProgress is always stuck at a certain number, is it because we need to play the video while it is downloading so when the user gets to a certain progress then the bufferProgress will start to progress again?

**Comment by se-bastiaan** [comment]
I'm not sure what you're trying to ask. It sounds like you are experiencing a bug like #56 which is most likely a result of #49.

**Comment by nostupidity** [comment]
Yes, I think its close to #56 issue, you said in #49 
> These logcats use the same torrent as sample. Find a good seeded one to reproduce.

I have to tell you I have little knowledge of how torrent works, where do I find a seeder? Is it with the TorrentHandle object?
