### ISSUE TITLE
Error calling alert listener

### ISSUE THREAD

**Issue by Tim-W** [TorrentStream/TorrentStream-Android#65]
Using version 2.7.0.
When trying to implement the onStreamProgress hook, for some files (they are all music flac files between 10 and 50 MB) the following happens:
```
I/SessionManager: Error calling alert listener: length=62; index=-400
I/SessionManager: Error calling alert listener: length=62; index=-399
I/SessionManager: Error calling alert listener: length=62; index=-398
I/SessionManager: Error calling alert listener: length=62; index=-397
I/SessionManager: Error calling alert listener: length=62; index=-396
I/SessionManager: Error calling alert listener: length=62; index=-459
I/SessionManager: Error calling alert listener: length=62; index=-455
I/SessionManager: Error calling alert listener: length=62; index=-456
I/SessionManager: Error calling alert listener: length=62; index=-462
I/SessionManager: Error calling alert listener: length=62; index=-461
I/SessionManager: Error calling alert listener: length=62; index=-458
```
Perhaps this is a bug with interaction with JLibtorrent?

**Comment by se-bastiaan** [comment]
This is only for some files? Have you tried using a previous version? I usually only test if the sample is still working.

I would indeed say that something in the listener is going wrong, look at [the code of jlibtorrent](https://github.com/frostwire/frostwire-jlibtorrent/blob/master/src/main/java/com/frostwire/jlibtorrent/SessionManager.java#L1025). But the error is not really something I understand. Especially since it is not clear what type of alert is being sent here. It can be a PIECE_FINISHED_ or BLOCK_FINISHED.

What does you listener look like?

**Comment by Tim-W** [comment]
I am still unsure how this error occurs. However I built an app running only jlibtorrent (without the torrentstream-android layer) and the message still sometimes comes up. I guess this can be closed as I cannot find a clear reason for the error message to be a result from torrentstream-android

**Comment by se-bastiaan** [comment]
Maybe it would be worth trying [libtorrent4j](https://github.com/aldenml/libtorrent4j)? It is a different fork. But if the problem is within libtorrent (the C layer) itself then I don't know what could be the problem.

**Comment by Tim-W** [comment]
I think it has to do with putting priorities higher than Priority.IGNORE on pieces that are outside of the videoFile

**Comment by se-bastiaan** [comment]
Yes that makes perfect sense, the Torrent class' `hasPieces` is only sized based on the selected file using the start and end pieces with `lastPieceIndex - firstPieceIndex + 1`.

You can try to catch the error by creating your own Torrent class and overridee the `alert` function. It should be public. Then you can see the actual exception.
