### ISSUE TITLE
Doesn't work on Android 11

### ISSUE THREAD

**Issue by FunkyMuse** [TorrentStream/TorrentStream-Android#70]
If you build the sample with targetSdkVersion 30
It won't fetch the magnet

Inside TorrentStream.java
`byte[] data = torrentSession.fetchMagnet(torrentUrl, 30);`

This is where it doesn't work.

**Comment by CraZyLegenD** [comment]
It won't work even if you update jlib to 1.2.8.0
I think it's Android 11 (targetSdkVersion 30) related issue since it works flawlessly on <30

**Comment by se-bastiaan** [comment]
Well it does make a lot of sense that it would not work if it has never been tested to do so. Any investigations in why this is happening are welcome. I would suggest upgrading to 1.2.10 of jlibtorrent first though.

**Comment by CraZyLegenD** [comment]
> Well it does make a lot of sense that it would not work if it has never been tested to do so. Any investigations in why this is happening are welcome. I would suggest upgrading to 1.2.10 of jlibtorrent first though.

Tried updating to that version too, didn't work either.

There's a timeout always happening when fetching the magnet, the library returns null all the time, even on 1.2.10.0

**Comment by dovahkrid** [comment]
> I see you already escalated the issue to jlibtorrent, let's keep this issue open and wait what the conclusion there is. [frostwire/frostwire-jlibtorrent#238](https://github.com/frostwire/frostwire-jlibtorrent/issues/238)

It got fixed. Waiting for this issue now.

**Comment by se-bastiaan** [comment]
Cool! Hope I will have some time to update. PR is welcome too 😁

**Comment by viettranhoang** [comment]
@se-bastiaan  I have created PR to update jlibtorrent to latest version and working perfectly on Android 11.
https://github.com/TorrentStream/TorrentStream-Android/pull/77

**Comment by FunkyMuse** [comment]
> @se-bastiaan I have created PR to update jlibtorrent to latest version and working perfectly on Android 11. #77

Works well, great job!
