### ISSUE TITLE
Sample with working seekbar

### ISSUE THREAD

**Issue by phanijsp** [TorrentStream/TorrentStream-Android#71]
Hi, Can you please provide a sample with working seekbar

**Comment by se-bastiaan** [comment]
I'm not sure what you question is. A seekbar? This is not a video player library.

**Comment by phanijsp** [comment]
My bad. I've got it working. Thanks for the the library

**Comment by maxakash** [comment]
> My bad. I've got it working. Thanks for the the library
Hey @phanijsp 
Can you please share the code?

**Comment by phanijsp** [comment]
@maxakash 
Yes you can. In onStreamReady you'll get the torrent. From that torrent you can get the video file and feed it to the player. You can refer to the below sample.
https://github.com/TorrentStream/TorrentStream-Android/blob/develop/sample/src/main/java/com/github/se_bastiaan/torrentstreamer/sample/MainActivity.kt
