### ISSUE TITLE
Stream via exo player

### ISSUE THREAD

**Issue by AMWolfstein** [TorrentStream/TorrentStream-Android#73]
Hello developer ,
I have project to steam movies and tv shows online for android device and wants to configure exo player to stream torrent content instead of mkv extension. How can I do this ? . Sorry for that as it's my first time for me to edit and i tried to get any guidance on this but i couldn't find .

**Comment by se-bastiaan** [comment]
Well this library only downloads any media file. Then you need to open the media file using exo player?

**Comment by AMWolfstein** [comment]
> Well this library only downloads any media file. Then you need to open the media file using exo player?

When i choose movie or episode for example and click on play . It will stream torrent file directly through exo player

**Comment by se-bastiaan** [comment]
Well no, you start downloading the torrent file using TorrentStream and then you open _the video file_ in ExoPlayer.
