### ISSUE TITLE
Please upgrade the library to jlibtorrent 1.2.16.0

### ISSUE THREAD

**Issue by maxakash** [TorrentStream/TorrentStream-Android#82]
Hey @se-bastiaan , please update the jlibtorrent to 1.2.16.0 and also update other dependencies.

Thanks for this wonderful library.

**Comment by maxakash** [comment]
> As you might have noticed in the commit history, a PR gets you very far in updating those kinds of things. No need to mention anyone tho, GitHub does notifications very well.
> 
> That said, I pushed changes 10 minutes ago migrating to libtorrent4j.

My bad. Thanks anyways for updating it.

**Comment by se-bastiaan** [comment]
I won't release a new version without knowing it actually works.

You can just use the hash as a version to use the latest commit.
